name: sdg-accelerator
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - numpy=1.22.*
  - pandas=1.4.*
  - scikit-learn=1.1.*
  - tqdm
  - requests=2.28.*
  - flask=2.2.*
  - spacy=3.4.*
  - spacy-model-en_core_web_sm=3.4.*
  - pip
  - pip:
    - pdfplumber==0.7.4
